root <- normalizePath(file.path(getwd()), winslash = "/", mustWork = FALSE)
Sys.setenv(DALYCARE_MIN_CELL_COUNT = "1")
source(file.path(root, "tests", "helper.R"))
source_test_runtime(root)

out_root <- tempfile("atlas_runs_")
result <- run_atlas(
  project_root = root,
  source_map_path = file.path(root, "config", "source-map.example.tsv"),
  output_root = out_root,
  mode = "report"
)

expect_file(file.path(result$run_dir, "outputs", "atlas_resource_catalog.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_source_resolution.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_dalycare_access.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_memory_plan.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_db_query_log.tsv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_db_budget_actions.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_sources.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_columns.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_column_profiles.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_column_top_values.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_checks.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_value_frequencies.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_semantic_data_dictionary.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_semantic_value_map.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_semantic_code_map.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_semantic_panel_links.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_clinical_concepts.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_domain_panels.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_panel_kpis.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_panel_distributions.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_panel_raw_fields.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_panel_parity.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_run_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_run_action_items.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "lab_npu_code_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_dictionary_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_dictionary_vectors.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_lab_usage_by_vector.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_lab_unmatched_codes.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_detective_code_inventory.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_detective_candidates.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_detective_source_year.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "isotype_code_usage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "isotype_bucket_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "mm_treatment_code_counts.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "mm_treatment_source_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "diagnosis_icd_groups.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "damyda_feature_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "registry_clinical_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "damyda_clinical_profile.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "damyda_numeric_fields.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "lyfo_clinical_profile.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "cll_clinical_profile.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_coverage_years.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_date_quality.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_spatial_region_counts.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_spatial_region_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_dk_choropleth_regions.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_streaming_progress_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "situation_report_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "situation_report_breakdowns.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "situation_report_freshness.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_module_readiness.csv"))
expect_file(file.path(result$run_dir, "outputs", "output_manifest.csv"))
expect_file(file.path(result$run_dir, "logs", "atlas_execution_log.tsv"))
expect_file(file.path(result$run_dir, "logs", "atlas_memory_log.tsv"))
expect_file(result$html)
expect_file(result$payload)

html <- paste(readLines(result$html, warn = FALSE), collapse = "\n")
expect_true(grepl("DALYCARE_atlas_payload.js", html, fixed = TRUE), "HTML should reference external payload JS.")
expect_false(grepl("window.DALYCARE_ATLAS_PAYLOAD =", html, fixed = TRUE), "HTML should not embed the full payload.")
expect_true(grepl("<meta name=\"author\" content=\"Alexander Owen Taylor\">", html, fixed = TRUE), "HTML should include transparent author metadata.")
expect_true(grepl("Built by Alexander Owen Taylor", html, fixed = TRUE), "HTML should include visible generated-atlas credit.")
expect_true(grepl("tab-overview", html, fixed = TRUE), "HTML should include the Overview tab.")
expect_true(grepl("tab-variables", html, fixed = TRUE), "HTML should include the Clinical Variables tab.")
expect_true(grepl("tab-situation", html, fixed = TRUE), "HTML should include the Situation Report tab.")
expect_true(grepl("tab-quickstart", html, fixed = TRUE), "HTML should include the Quick Start tab.")
expect_true(grepl("tab-dictionary", html, fixed = TRUE), "HTML should include the Data Dictionary tab.")
expect_true(grepl("tab-registries", html, fixed = TRUE), "HTML should include the Disease Registries tab.")
expect_true(grepl("tab-clinical", html, fixed = TRUE), "HTML should include the Clinical Data tab.")
expect_true(grepl("tab-treatment", html, fixed = TRUE), "HTML should include the Treatment tab.")
expect_true(grepl("tab-laboratory", html, fixed = TRUE), "HTML should include the Laboratory tab.")
expect_true(grepl("tab-ehr", html, fixed = TRUE), "HTML should include the EHR Modules tab.")
expect_true(grepl("tab-infrastructure", html, fixed = TRUE), "HTML should include the Infrastructure tab.")
expect_true(grepl("data-sub=\"overview-temporal\"", html, fixed = TRUE), "HTML should include temporal coverage sub-tabs.")
expect_true(grepl("data-sub=\"overview-spatial\"", html, fixed = TRUE), "HTML should include regional coverage sub-tabs.")
expect_true(grepl("data-sub=\"situation-headlines\"", html, fixed = TRUE), "HTML should include Situation Report sub-tabs.")
expect_true(grepl("data-sub=\"dictionary-lineage\"", html, fixed = TRUE), "HTML should include semantic dictionary sub-tabs.")
expect_true(grepl("data-sub=\"reg-damyda\"", html, fixed = TRUE), "HTML should include DaMyDa registry sub-tabs.")
expect_true(grepl("data-sub=\"clinical-diagnoses\"", html, fixed = TRUE), "HTML should include clinical module sub-tabs.")
expect_true(grepl("data-sub=\"tx-codes\"", html, fixed = TRUE), "HTML should include treatment-code sub-tabs.")
expect_true(grepl("data-sub=\"lab-npu\"", html, fixed = TRUE), "HTML should include laboratory/NPU sub-tabs.")
expect_true(grepl("data-sub=\"ehr-sp\"", html, fixed = TRUE), "HTML should include EHR module sub-tabs.")
expect_true(grepl("data-sub=\"infra-actions\"", html, fixed = TRUE), "HTML should include run action item sub-tabs.")
expect_true(grepl("data-sub=\"infra-catalog\"", html, fixed = TRUE), "HTML should include infrastructure sub-tabs.")
expect_true(grepl("catalog-search", html, fixed = TRUE), "HTML should include source catalog search.")
expect_true(grepl("catalog-domain-filter", html, fixed = TRUE), "HTML should include domain filtering controls.")
expect_true(grepl("catalog-status-filter", html, fixed = TRUE), "HTML should include status filtering controls.")
expect_true(grepl("catalog-role-filter", html, fixed = TRUE), "HTML should include role filtering controls.")
expect_true(grepl("column-search", html, fixed = TRUE), "HTML should include column search.")
expect_true(grepl("column-dataset-filter", html, fixed = TRUE), "HTML should include column dataset filtering.")
expect_true(grepl("column-domain-filter", html, fixed = TRUE), "HTML should include column domain filtering.")
expect_true(grepl("column-kind-filter", html, fixed = TRUE), "HTML should include column profile-kind filtering.")
expect_true(grepl("clinical-variable-search", html, fixed = TRUE), "HTML should include Clinical Variables search.")
expect_true(grepl("clinical-variable-cards", html, fixed = TRUE), "HTML should include Clinical Variables concept cards.")
expect_true(grepl("renderDomainPanel", html, fixed = TRUE), "HTML should include the product-layer domain panel renderer.")
expect_true(grepl("function renderVitalsPanel()", html, fixed = TRUE), "HTML should include the dedicated Vitals renderer.")
expect_true(grepl("function renderSocialHistoryPanel()", html, fixed = TRUE), "HTML should include the dedicated Social History renderer.")
expect_false(grepl("setHtml(\"clinical-vitals-cards\", renderDomainPanel(\"clinical_vitals\"))", html, fixed = TRUE), "Vitals should not be rendered through the generic domain panel renderer.")
expect_false(grepl("setHtml(\"clinical-social-cards\", renderDomainPanel(\"clinical_social_history\"))", html, fixed = TRUE), "Social History should not be rendered through the generic domain panel renderer.")
expect_false(grepl("Vitals Sources", html, fixed = TRUE), "Vitals heading should no longer say Vitals Sources.")
expect_false(grepl("Social History Sources", html, fixed = TRUE), "Social History heading should no longer say Social History Sources.")
expect_true(grepl("Vital signs and anthropometrics", html, fixed = TRUE), "Vitals heading should use the clinician-facing title.")
expect_true(grepl("Social history: smoking and alcohol", html, fixed = TRUE), "Social History heading should use the clinician-facing title.")
vaegt <- paste0("V", intToUtf8(0x00E6), "gt")
hoejde <- paste0("H", intToUtf8(0x00F8), "jde")
for (needle in c("SP_VitaleVaerdier", "patientid", "displayname", "numericvalue", vaegt, hoejde)) {
  expect_true(grepl(needle, html, fixed = TRUE), paste("Vitals renderer should visibly contain:", needle))
}
for (needle in c("SP_Social_Hx", "ryger", "drikker", "Er holdt op", "Aldrig", "Ja", "Ikke spurgt", "Passiv", "Ikke aktuelt", "Udskyd")) {
  expect_true(grepl(needle, html, fixed = TRUE), paste("Social History renderer should visibly contain:", needle))
}
expect_true(grepl("jumpToClinicalConcept", html, fixed = TRUE), "Concept-link buttons should use the Clinical Variables search/filter path.")
expect_true(grepl("Repeated measures", html, fixed = TRUE) && grepl("baseline window", html, fixed = TRUE) && grepl("outlier filtering", html, fixed = TRUE), "Vitals renderer should include the required caveat.")
expect_true(grepl("Unknown and true missing were not separately quantified in this output", html, fixed = TRUE), "Social History renderer should include the unknown/missing evidence note.")
expect_true(grepl("Row-level social-history observations do not necessarily equal current patient-level status", html, fixed = TRUE), "Social History renderer should include the row-level caveat.")
expect_true(grepl("Patients", html, fixed = TRUE), "Vitals stat cards should render patient-count fields.")
expect_true(grepl("<span class=\"mini\">Unit</span><b>${escapeHtml(unit || \"not available\")}</b>", html, fixed = TRUE), "Vitals stat cards should render units with a not-available fallback.")
expect_true(grepl("renderVitalsStatCard(\"Weight\", [\"Vægt\", \"Vaegt\", \"VÃ¦gt\"], \"weight\", \"kg\")", html, fixed = TRUE), "Vitals stat cards should render kg for weight.")
expect_true(grepl("renderVitalsStatCard(\"Height\", [\"Højde\", \"Hoejde\", \"HÃ¸jde\"], \"height\", \"cm\")", html, fixed = TRUE), "Vitals stat cards should render cm for height.")
expect_true(grepl("scope: mixed; displayed distributions are cartography_scan", html, fixed = TRUE) || grepl("scope: displayed distributions are cartography_scan", html, fixed = TRUE), "Vitals/Social renderer should expose cartography-scan scope.")
bmi_label <- paste("BMI", intToUtf8(0x2014), "derived from height and weight")
expect_true(grepl(bmi_label, html, fixed = TRUE), "Vitals lineage should label BMI as derived from height and weight.")
expect_true(grepl("const priorityRows = [weightRow, heightRow, numericRow].filter(Boolean)", html, fixed = TRUE), "Vitals renderer should order priority raw lineage as Vægt, Højde, numericvalue.")
expect_true(grepl("semantic-search", html, fixed = TRUE), "HTML should include semantic dictionary search.")
expect_true(grepl("semantic-group-filter", html, fixed = TRUE), "HTML should include semantic dictionary group filtering.")
expect_true(grepl("semantic-panel-filter", html, fixed = TRUE), "HTML should include semantic dictionary panel filtering.")
expect_true(grepl("semantic-detail", html, fixed = TRUE), "HTML should include semantic lineage detail drawer.")
expect_true(grepl("Key raw fields", html, fixed = TRUE), "HTML domain panels should include key raw fields blocks.")
expect_true(grepl("qa-severity-filter", html, fixed = TRUE), "HTML should include QA filtering controls.")
expect_true(grepl("run-action-items", html, fixed = TRUE), "HTML should include action item containers.")
expect_true(grepl("action-summary-cards", html, fixed = TRUE), "HTML should include action item summary cards.")
expect_true(grepl("streaming-progress-cards", html, fixed = TRUE), "HTML should include DB streaming progress cards.")
expect_true(grepl("temporal-date-quality-cards", html, fixed = TRUE), "HTML should include temporal date-quality cards.")
expect_true(grepl("infrastructure-streaming-progress", html, fixed = TRUE), "HTML should include DB streaming progress tables.")
expect_true(grepl("infrastructure-temporal-date-quality", html, fixed = TRUE), "HTML should include temporal date-quality tables.")
expect_true(grepl("panel-nav", html, fixed = TRUE), "HTML should include panel navigation.")
expect_true(grepl("temporal-heatmap", html, fixed = TRUE), "HTML should include a temporal coverage heatmap container.")
expect_true(grepl("dkMap", html, fixed = TRUE), "HTML should include a Denmark choropleth container.")
expect_true(grepl("regionMatrix", html, fixed = TRUE), "HTML should include a region coverage matrix container.")
expect_true(grepl("dk-region", html, fixed = TRUE), "HTML should include clickable Denmark region handlers.")
expect_true(grepl("situation-cards", html, fixed = TRUE), "HTML should include Situation Report card containers.")
expect_true(grepl("of cohort", html, fixed = TRUE), "Situation Report cards should show patient counts as a share of the cohort.")
expect_true(grepl("data as of", html, fixed = TRUE), "Situation Report cards should label source dates as data-as-of anchors.")
payload <- paste(readLines(result$payload, warn = FALSE), collapse = "\n")
expect_true(grepl("damyda_clinical_profile", payload, fixed = TRUE), "Payload should include the DaMyDa clinical profile panel.")
expect_true(grepl("lyfo_clinical_profile", payload, fixed = TRUE), "Payload should include the LYFO clinical profile panel.")
expect_true(grepl("cll_clinical_profile", payload, fixed = TRUE), "Payload should include the CLL clinical profile panel.")
expect_true(grepl("run_summary", payload, fixed = TRUE), "Payload should include run summary rows.")
expect_true(grepl("action_items", payload, fixed = TRUE), "Payload should include run action items.")
expect_true(grepl("action_summary", payload, fixed = TRUE), "Payload should include action item summaries.")
expect_true(grepl("db_query_log", payload, fixed = TRUE), "Payload should include DB query log diagnostics.")
expect_true(grepl("db_budget_actions", payload, fixed = TRUE), "Payload should include DB budget action diagnostics.")
expect_true(grepl("source_domains", payload, fixed = TRUE), "Payload should include source-domain summaries.")
expect_true(grepl("hero_metrics", payload, fixed = TRUE), "Payload should include hero metrics.")
expect_true(grepl("domain_cards", payload, fixed = TRUE), "Payload should include domain cards.")
expect_true(grepl("catalog_rows", payload, fixed = TRUE), "Payload should include catalog rows.")
expect_true(grepl("qa_items", payload, fixed = TRUE), "Payload should include QA items.")
expect_true(grepl("npu_cards", payload, fixed = TRUE), "Payload should include NPU dictionary cards.")
expect_true(grepl("detective_cards", payload, fixed = TRUE), "Payload should include NPU detective cards.")
expect_true(grepl("isotype_cards", payload, fixed = TRUE), "Payload should include isotype cards.")
expect_true(grepl("treatment_cards", payload, fixed = TRUE), "Payload should include treatment-code cards.")
expect_true(grepl("situation_report_cards", payload, fixed = TRUE), "Payload should include Situation Report cards.")
expect_true(grepl("registry_cards", payload, fixed = TRUE), "Payload should include registry cards.")
expect_true(grepl("panel_groups", payload, fixed = TRUE), "Payload should include panel groups.")
expect_true(grepl("column_profile_rows", payload, fixed = TRUE), "Payload should include column profile rows.")
expect_true(grepl("column_top_value_rows", payload, fixed = TRUE), "Payload should include column top value rows.")
expect_true(grepl("column_profile_summary", payload, fixed = TRUE), "Payload should include column profile summary.")
expect_true(grepl("semantic_dictionary_rows", payload, fixed = TRUE), "Payload should include semantic dictionary rows.")
expect_true(grepl("semantic_value_map_rows", payload, fixed = TRUE), "Payload should include semantic value map rows.")
expect_true(grepl("semantic_code_map_rows", payload, fixed = TRUE), "Payload should include semantic code map rows.")
expect_true(grepl("semantic_panel_links", payload, fixed = TRUE), "Payload should include semantic panel links.")
expect_true(grepl("clinical_concept_rows", payload, fixed = TRUE), "Payload should include Clinical Variables concept rows.")
expect_true(grepl("domain_panel_rows", payload, fixed = TRUE), "Payload should include product-layer domain panel rows.")
expect_true(grepl("panel_kpi_rows", payload, fixed = TRUE), "Payload should include product-layer KPI rows.")
expect_true(grepl("panel_distribution_rows", payload, fixed = TRUE), "Payload should include product-layer distribution rows.")
expect_true(grepl("panel_raw_field_rows", payload, fixed = TRUE), "Payload should include product-layer raw field rows.")
expect_true(grepl("panel_parity_rows", payload, fixed = TRUE), "Payload should include V33 panel parity rows.")
expect_true(grepl("review_clinical_variables", payload, fixed = TRUE), "Payload should include the Clinical Variables view model.")
expect_true(grepl("review_semantic_summary", payload, fixed = TRUE), "Payload should include semantic summary rows.")
expect_true(grepl("Smoking status", payload, fixed = TRUE), "Payload should expose clinician-facing semantic variables.")
expect_true(grepl("NPU02319", payload, fixed = TRUE), "Payload should expose aggregate NPU semantic code lineage.")
expect_true(grepl("builder_credit", payload, fixed = TRUE), "Payload should include transparent generated-atlas credit.")
expect_true(grepl("Built by Alexander Owen Taylor", payload, fixed = TRUE), "Payload should include the generated-atlas credit value.")
expect_true(grepl("review_scope_notes", payload, fixed = TRUE), "Payload should include review scope notes.")
expect_true(grepl("review_data_landscape", payload, fixed = TRUE), "Payload should include review data landscape.")
expect_true(grepl("review_module_readiness", payload, fixed = TRUE), "Payload should include module readiness.")
expect_true(grepl("review_streaming_summary", payload, fixed = TRUE), "Payload should include DB streaming progress summaries.")
expect_true(grepl("review_temporal_date_quality", payload, fixed = TRUE), "Payload should include temporal date-quality summaries.")
expect_true(grepl("review_domain_jump_links", payload, fixed = TRUE), "Payload should include review jump links.")
expect_true(grepl("review_nav", payload, fixed = TRUE), "Payload should include V33-style navigation.")
expect_true(grepl("review_overview", payload, fixed = TRUE), "Payload should include V33-style overview sections.")
expect_true(grepl("review_registry_sections", payload, fixed = TRUE), "Payload should include V33-style registry sections.")
expect_true(grepl("review_clinical_sections", payload, fixed = TRUE), "Payload should include V33-style clinical sections.")
expect_true(grepl("review_treatment_sections", payload, fixed = TRUE), "Payload should include V33-style treatment sections.")
expect_true(grepl("review_laboratory_sections", payload, fixed = TRUE), "Payload should include V33-style laboratory sections.")
expect_true(grepl("review_situation_sections", payload, fixed = TRUE), "Payload should include V33-style Situation Report sections.")
expect_true(grepl("review_ehr_sections", payload, fixed = TRUE), "Payload should include V33-style EHR sections.")
expect_true(grepl("review_infrastructure_sections", payload, fixed = TRUE), "Payload should include V33-style infrastructure sections.")
expect_true(grepl("review_temporal_coverage", payload, fixed = TRUE), "Payload should include V33-style temporal coverage sections.")
expect_true(grepl("review_spatial_coverage", payload, fixed = TRUE), "Payload should include V33-style spatial coverage sections.")
expect_true(grepl("review_dk_choropleth", payload, fixed = TRUE), "Payload should include V33-style Denmark choropleth sections.")
expect_false(grepl("\"aot|\"AOT|\"Alexander", payload), "Payload keys should not use personal or AOT naming.")
expect_false(grepl("patientid", payload, ignore.case = TRUE), "HTML payload should not expose id-like field names.")

freq <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_value_frequencies.csv"), stringsAsFactors = FALSE)
expect_false(any(freq$column_name == "patientid"), "Public value frequencies must not expose patient IDs.")

manifest <- utils::read.csv(file.path(result$run_dir, "outputs", "output_manifest.csv"), stringsAsFactors = FALSE)
expect_true(all(c("resource_catalog", "source_resolution", "dalycare_access", "memory_plan", "db_query_log", "db_budget_actions", "action_items", "sources", "columns", "column_profiles", "column_top_values", "checks", "value_frequencies", "semantic_dictionary", "semantic_value_map", "semantic_code_map", "semantic_panel_links", "clinical_concepts", "domain_panels", "panel_kpis", "panel_distributions", "panel_raw_fields", "panel_parity", "run_summary", "html", "payload", "memory_log") %in% manifest$artifact_id), "Manifest should list expected artifacts.")
expect_true(all(c("npu_dictionary_summary", "npu_dictionary_vectors", "npu_lab_usage_by_vector", "npu_lab_unmatched_codes", "npu_detective_code_inventory", "npu_detective_candidates", "npu_detective_source_year", "isotype_code_usage", "isotype_bucket_summary", "mm_treatment_code_counts", "mm_treatment_source_summary", "registry_clinical_summary", "damyda_clinical_profile", "damyda_numeric_fields", "lyfo_clinical_profile", "cll_clinical_profile") %in% manifest$artifact_id), "Manifest should list NPU, isotype, treatment, and registry panel artifacts.")
expect_true(all(c("atlas_temporal_coverage", "atlas_temporal_coverage_years", "atlas_spatial_region_counts", "atlas_spatial_region_coverage", "atlas_dk_choropleth_regions") %in% manifest$artifact_id), "Manifest should list V33 coverage panel artifacts.")
expect_true(all(c("atlas_temporal_date_quality", "atlas_streaming_progress_summary") %in% manifest$artifact_id), "Manifest should list date-quality and streaming-progress panel artifacts.")
expect_true(all(c("situation_report_summary", "situation_report_breakdowns", "situation_report_freshness") %in% manifest$artifact_id), "Manifest should list Situation Report panel artifacts.")
expect_true("atlas_module_readiness" %in% manifest$artifact_id, "Manifest should list the module readiness panel artifact.")
expect_false(any(grepl("aot|AOT|Alexander", manifest$artifact_id)), "Generated artifact IDs should use neutral names.")
expect_true(all(manifest$status == "ok"), "Manifest artifacts should exist.")

sources <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_sources.csv"), stringsAsFactors = FALSE)
expect_true(all(c("domain", "subdomain", "atlas_role") %in% names(sources)), "Source metadata should be preserved in atlas_sources.csv.")
expect_true(all(c("chosen_strategy", "memory_status", "resolution_status") %in% names(sources)), "Source rows should record memory-safe profiling decisions.")
expect_true(!any(sources$date_column_guess == "patientid"), "Patient identifiers should not be guessed as date columns.")
expect_true("2021-01-01" %in% sources$min_date, "Date ranges should be emitted as ISO dates.")

columns <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_columns.csv"), stringsAsFactors = FALSE)
column_profiles <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_column_profiles.csv"), stringsAsFactors = FALSE)
column_top_values <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_column_top_values.csv"), stringsAsFactors = FALSE)
expect_equal(nrow(column_profiles), nrow(columns), "Run output should include one column profile per profiled column.")
expect_true(any(column_profiles$profile_kind == "numeric"), "Column profile output should include numeric summaries when numeric columns exist.")
expect_true(any(column_profiles$profile_kind == "date"), "Column profile output should include date summaries when date columns exist.")
expect_false(any(column_top_values$column_name == "patientid"), "Column top values must not expose patient identifier columns.")
expect_true(all(c("domain", "subdomain", "atlas_role") %in% names(column_profiles)), "Column profiles should retain source metadata.")

catalog <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_resource_catalog.csv"), stringsAsFactors = FALSE)
expect_true(all(c("domain", "subdomain", "atlas_role") %in% names(catalog)), "Source metadata should be preserved in the resource catalog.")

damyda_clinical <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "damyda_clinical_profile.csv"), stringsAsFactors = FALSE)
expect_true(any(damyda_clinical$facet == "stage"), "Run output should include DaMyDa stage summary.")
expect_false(any(damyda_clinical$source_column == "patientid"), "Run output registry panels must not expose patient identifier columns.")

damyda_numeric <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "damyda_numeric_fields.csv"), stringsAsFactors = FALSE)
expect_true(any(damyda_numeric$field == "albumin"), "Run output should include DaMyDa albumin aggregate summary.")
expect_false(any(c("value", "examples", "distinct_sample") %in% names(damyda_numeric)), "Run output numeric registry panel should be aggregate-only.")

npu_summary <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_dictionary_summary.csv"), stringsAsFactors = FALSE)
npu_vectors <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_dictionary_vectors.csv"), stringsAsFactors = FALSE)
npu_usage <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_lab_usage_by_vector.csv"), stringsAsFactors = FALSE)
npu_unmatched <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_lab_unmatched_codes.csv"), stringsAsFactors = FALSE)
npu_inventory <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_detective_code_inventory.csv"), stringsAsFactors = FALSE)
npu_candidates <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_detective_candidates.csv"), stringsAsFactors = FALSE)
isotype_usage <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "isotype_code_usage.csv"), stringsAsFactors = FALSE)
isotype_buckets <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "isotype_bucket_summary.csv"), stringsAsFactors = FALSE)
mm_counts <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "mm_treatment_code_counts.csv"), stringsAsFactors = FALSE)
mm_sources <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "mm_treatment_source_summary.csv"), stringsAsFactors = FALSE)
temporal_coverage <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_coverage.csv"), stringsAsFactors = FALSE)
temporal_years <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_coverage_years.csv"), stringsAsFactors = FALSE)
temporal_quality <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_date_quality.csv"), stringsAsFactors = FALSE)
streaming_progress <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_streaming_progress_summary.csv"), stringsAsFactors = FALSE)
spatial_counts <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_spatial_region_counts.csv"), stringsAsFactors = FALSE)
spatial_coverage <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_spatial_region_coverage.csv"), stringsAsFactors = FALSE)
dk_regions <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_dk_choropleth_regions.csv"), stringsAsFactors = FALSE)
expect_true("dictionary_codes" %in% npu_summary$metric, "Run output should include NPU dictionary summary.")
expect_true(any(npu_vectors$consensus_vector == "CREATININE_CODES"), "Run output should include NPU dictionary vector summaries.")
expect_true(any(npu_usage$consensus_vector == "CREATININE_CODES"), "Run output should include observed NPU usage by consensus vector.")
expect_true(any(npu_unmatched$npu_code == "NPU99999"), "Run output should include suppressed-safe unmatched NPU code summaries.")
expect_true(any(npu_inventory$surface == "renal_creatinine"), "Run output should include NPU detective surface classifications.")
expect_true(any(npu_candidates$npu_code == "NPU99999"), "Run output should include NPU detective candidates.")
expect_true(any(isotype_usage$isotype_family == "IgG"), "Run output should include isotype finder usage.")
expect_true(any(isotype_buckets$bucket == "heavy_chain"), "Run output should include isotype bucket summaries.")
expect_true(any(mm_counts$code == "BWHA154"), "Run output should count exact MM treatment codes.")
expect_true(any(mm_counts$code == "BWG"), "Run output should count MM treatment prefix codes.")
expect_true(nrow(mm_sources) > 0, "Run output should summarize treatment evidence sources.")
expect_true(any(temporal_coverage$table_name == "example_labs" & temporal_coverage$display_min_year == 2021), "Run output should include clamped temporal coverage by source.")
expect_true(any(temporal_years$table_name == "example_labs" & temporal_years$year == 2021), "Run output should include temporal coverage year counts.")
expect_true(all(c("issue_type", "message") %in% names(temporal_quality)), "Run output should include temporal date-quality audit columns.")
expect_true(all(c("streamed_columns", "total_chunks", "slowest_column") %in% names(streaming_progress)), "Run output should include DB streaming progress summary columns.")
expect_true(any(spatial_counts$table_name == "example_damyda" & spatial_counts$region_code == "1084"), "Run output should include aggregate DaMyDa region counts.")
expect_true(any(spatial_coverage$region_code == "1084"), "Run output should include region coverage matrix rows.")
expect_equal(sum(as.logical(dk_regions$map_include)), 5L, "Denmark choropleth should include the five Danish regions.")
expect_false(any(dk_regions$region_code == "1099" & as.logical(dk_regions$map_include)), "Other/unknown region should not be shaded on the map.")

run_summary <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_run_summary.csv"), stringsAsFactors = FALSE)
expect_true(all(c("builder_credit", "mapped_sources", "loaded_sources", "skipped_sources", "panel_rows", "min_cell_count", "db_aggregate_sources", "dataset_full_load_fallback_sources") %in% run_summary$metric), "Run summary should include compact run, credit, and memory metrics.")
expect_true("Built by Alexander Owen Taylor" %in% run_summary$value[run_summary$metric == "builder_credit"], "Run summary should record the generated-atlas credit.")
expect_true("1" %in% run_summary$value[run_summary$metric == "min_cell_count"], "Run summary should record the active minimum cell count.")

action_items <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_run_action_items.csv"), stringsAsFactors = FALSE)
expect_true(all(c("severity", "action_id", "recommended_action") %in% names(action_items)), "Run action items should include severity, action id, and operator action columns.")

semantic_dictionary <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_semantic_data_dictionary.csv"), stringsAsFactors = FALSE)
semantic_value_map <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_semantic_value_map.csv"), stringsAsFactors = FALSE)
semantic_code_map <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_semantic_code_map.csv"), stringsAsFactors = FALSE)
semantic_panel_links <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_semantic_panel_links.csv"), stringsAsFactors = FALSE)
clinical_concepts <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_clinical_concepts.csv"), stringsAsFactors = FALSE)
domain_panels <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_domain_panels.csv"), stringsAsFactors = FALSE)
panel_kpis <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_panel_kpis.csv"), stringsAsFactors = FALSE)
panel_distributions <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_panel_distributions.csv"), stringsAsFactors = FALSE)
panel_raw_fields <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_panel_raw_fields.csv"), stringsAsFactors = FALSE)
panel_parity <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_panel_parity.csv"), stringsAsFactors = FALSE)
expect_true(any(semantic_dictionary$raw_column == "ryger" & semantic_dictionary$clinical_variable == "Smoking status"), "Semantic output should map ryger to Smoking status.")
expect_true(any(semantic_dictionary$raw_column == "drikker" & semantic_dictionary$clinical_variable == "Alcohol use"), "Semantic output should map drikker to Alcohol use.")
expect_true(any(semantic_dictionary$raw_descriptor == "Vægt" & semantic_dictionary$clinical_variable == "Weight"), "Semantic output should map Vægt to Weight.")
expect_true(any(semantic_dictionary$raw_descriptor == "Højde" & semantic_dictionary$clinical_variable == "Height"), "Semantic output should map Højde to Height.")
expect_true(any(semantic_dictionary$raw_column == "Reg_LDH" & semantic_dictionary$clinical_variable == "LDH"), "Semantic output should map Reg_LDH to LDH.")
expect_true(any(semantic_dictionary$raw_column == "Reg_Creatinin_mikmoll" & semantic_dictionary$clinical_variable == "Creatinine"), "Semantic output should map Reg_Creatinin_mikmoll to creatinine.")
expect_true(any(semantic_dictionary$raw_code == "NPU02319" & semantic_dictionary$clinical_variable == "Haemoglobin"), "Semantic output should map NPU02319 to haemoglobin.")
expect_true(any(semantic_dictionary$raw_code == "DNK35302" & semantic_dictionary$clinical_variable == "eGFR"), "Semantic output should map DNK35302 to eGFR.")
expect_true(any(semantic_dictionary$raw_code == "NPU19748" & semantic_dictionary$clinical_variable == "Leukocytes"), "Semantic output should map NPU19748 to leukocytes.")
expect_true(any(semantic_value_map$raw_column == "ryger" & semantic_value_map$display_value == "Former smoker"), "Semantic value map should include smoking value meanings.")
expect_true(any(semantic_code_map$code_system == "ATC"), "Semantic code map should include ATC treatment signals.")
expect_true(any(semantic_code_map$code_system == "SKS"), "Semantic code map should include SKS signals.")
expect_true(any(semantic_code_map$code_system == "SNOMED"), "Semantic code map should include SNOMED pathology signals.")
expect_true(nrow(semantic_panel_links) > 0, "Semantic panel links should be generated.")
expect_true(all(nzchar(semantic_dictionary$evidence_file)), "Every semantic row should include an evidence file.")
expect_false(any(vapply(semantic_dictionary$raw_column, is_sensitive_column, logical(1))), "Semantic dictionary should not turn identifier-like columns into variables.")
expect_false(any(grepl("[.](tsv|csv)$", semantic_dictionary$source_name, ignore.case = TRUE)), "Semantic source names should not be cartography evidence filenames.")
expect_true(all(c("height", "weight", "bmi", "smoking_status", "alcohol_use", "ldh", "haemoglobin", "creatinine", "egfr", "imaging_availability", "microbiology_infection_data") %in% clinical_concepts$clinical_concept_id), "Clinical concept output should include required clinician-facing concept cards.")
expect_true(any(panel_raw_fields$source_name == "SP_VitaleVaerdier"), "Panel raw fields should include SP_VitaleVaerdier rows.")
expect_true(any(panel_raw_fields$source_name %in% c("SP_Social_Hx", "SP_SocialHX")), "Panel raw fields should include SP_Social_Hx rows.")
expect_true(any(panel_raw_fields$source_name == "SP_VitaleVaerdier" & panel_raw_fields$raw_column == "displayname" & panel_raw_fields$raw_descriptor == vaegt), "Panel raw fields should include SP_VitaleVaerdier displayname=Vægt.")
expect_true(any(panel_raw_fields$source_name == "SP_VitaleVaerdier" & panel_raw_fields$raw_column == "displayname" & panel_raw_fields$raw_descriptor == hoejde), "Panel raw fields should include SP_VitaleVaerdier displayname=Højde.")
expect_true(any(panel_raw_fields$source_name == "SP_VitaleVaerdier" & panel_raw_fields$raw_column == "numericvalue"), "Panel raw fields should include SP_VitaleVaerdier numericvalue.")
vital_raw <- panel_raw_fields[panel_raw_fields$panel_id == "clinical_vitals", , drop = FALSE]
priority_labels <- c(
  vital_raw$raw_field_label[which(vital_raw$raw_column == "displayname" & vital_raw$raw_descriptor == vaegt)[1]],
  vital_raw$raw_field_label[which(vital_raw$raw_column == "displayname" & vital_raw$raw_descriptor == hoejde)[1]],
  vital_raw$raw_field_label[which(vital_raw$raw_column == "numericvalue")[1]]
)
priority_labels <- priority_labels[!is.na(priority_labels)]
priority_renderable <- paste(priority_labels, collapse = "\n")
expect_true(grepl(vaegt, priority_renderable, fixed = TRUE), "Renderable Vitals priority lineage should contain Vægt.")
expect_true(grepl(hoejde, priority_renderable, fixed = TRUE), "Renderable Vitals priority lineage should contain Højde.")
expect_true(grepl("numericvalue", priority_renderable, fixed = TRUE), "Renderable Vitals priority lineage should contain numericvalue.")
expect_true(regexpr(vaegt, priority_renderable, fixed = TRUE)[[1]] < regexpr(hoejde, priority_renderable, fixed = TRUE)[[1]], "Renderable Vitals priority lineage should place Vægt before Højde.")
expect_true(regexpr(hoejde, priority_renderable, fixed = TRUE)[[1]] < regexpr("numericvalue", priority_renderable, fixed = TRUE)[[1]], "Renderable Vitals priority lineage should place Højde before numericvalue.")
expect_true(any(panel_raw_fields$raw_column == "ryger" & panel_raw_fields$clinical_variable == "Smoking status"), "Panel raw fields should include ryger to Smoking status.")
expect_true(any(panel_raw_fields$source_name %in% c("SP_Social_Hx", "SP_SocialHX") & panel_raw_fields$raw_column == "ryger"), "Panel raw fields should include SP_Social_Hx.ryger.")
expect_true(any(panel_raw_fields$raw_column == "numericvalue" & panel_raw_fields$clinical_variable == "Vital numeric measurement value"), "Panel raw fields should include numericvalue as the vital measurement value.")
expect_true(any(panel_raw_fields$source_name %in% c("SP_Social_Hx", "SP_SocialHX") & panel_raw_fields$raw_column == "drikker"), "Panel raw fields should include SP_Social_Hx.drikker.")
expect_true(any(panel_raw_fields$raw_code == "NPU02319" & panel_raw_fields$clinical_variable == "Haemoglobin"), "Panel raw fields should include NPU02319 to Haemoglobin.")
expect_true(any(panel_distributions$panel_id == "clinical_social_history" & panel_distributions$raw_column == "ryger" & panel_distributions$display_value == "Former smoker"), "Social History panel distributions should include smoking value maps.")
expect_true(any(panel_distributions$panel_id == "clinical_social_history" & panel_distributions$raw_column == "drikker" & panel_distributions$display_value == "Alcohol use yes"), "Social History panel distributions should include alcohol value maps.")
expect_false(any(panel_distributions$panel_id == "clinical_social_history" & panel_distributions$raw_column == "ryger" & panel_distributions$raw_value == "Ja" & panel_distributions$display_value == "Alcohol use yes"), "Smoking Ja should not be grouped as alcohol use.")
expect_false(any(panel_distributions$panel_id == "clinical_social_history" & panel_distributions$raw_column == "drikker" & panel_distributions$raw_value == "Ja" & panel_distributions$display_value == "Current smoker"), "Alcohol Ja should not be grouped as current smoker.")
expect_equal(sum(clinical_concepts$clinical_concept_id == "bmi"), 1L, "Clinical concept output should contain only one BMI row.")
expect_true(grepl("derived from height and weight", clinical_concepts$purpose[clinical_concepts$clinical_concept_id == "bmi"], ignore.case = TRUE), "BMI concept should be described as derived from height and weight.")
if (any(clinical_concepts$clinical_concept_id %in% c("weight", "height") & !is.na(clinical_concepts$n_patients))) {
  expect_true(grepl("patientCountForConcept", html, fixed = TRUE), "Vitals renderer should use concept patient counts when available.")
}
expect_true(any(domain_panels$panel_id == "clinical_vitals" & grepl("Repeated measures", domain_panels$caveats, fixed = TRUE)), "Vitals product panel should carry repeated-measures caveat.")
expect_true(any(panel_distributions$panel_id == "clinical_imaging" & panel_distributions$display_value == "EHR-native imaging metadata/report text"), "Imaging panel should preserve EHR-native imaging layer.")
expect_true(any(panel_distributions$panel_id == "clinical_microbiology" & grepl("SP blood-culture workflow", panel_distributions$display_value, fixed = TRUE)), "Microbiology panel should include SP blood-culture workflow.")
expect_true(all(c("old_panel_id", "new_panel_id", "old_title", "new_title", "parity_status", "missing_items", "next_required_output") %in% names(panel_parity)), "Panel parity should use the required schema.")
expect_true(all(c("restored", "partial", "placeholder") %in% c(panel_parity$parity_status, "partial", "placeholder")), "Panel parity should use allowed statuses.")
for (panel_id in domain_panels$panel_id[domain_panels$parity_status == "restored"]) {
  expect_true(any(panel_raw_fields$panel_id == panel_id), paste("Restored panel should have raw fields:", panel_id))
  expect_true(any(panel_kpis$panel_id == panel_id) || any(panel_distributions$panel_id == panel_id), paste("Restored panel should have KPIs/distributions:", panel_id))
}

situation_summary <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "situation_report_summary.csv"), stringsAsFactors = FALSE)
expect_true(all(c("definition_basis", "n_cohort", "pct_cohort") %in% names(situation_summary)), "Situation Report summary should include definition and cohort-audit columns.")

log_text <- paste(readLines(file.path(result$run_dir, "logs", "atlas_execution_log.tsv"), warn = FALSE), collapse = "\n")
expect_true(grepl("Run summary:", log_text, fixed = TRUE), "Execution log should include a run summary line.")

memory_plan <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_memory_plan.csv"), stringsAsFactors = FALSE)
expect_true(all(memory_plan$chosen_strategy == "file_full_load"), "Fixture file sources should use the file full-load strategy.")
memory_log <- utils::read.delim(file.path(result$run_dir, "logs", "atlas_memory_log.tsv"), stringsAsFactors = FALSE)
expect_true(all(c("chosen_strategy", "memory_status", "max_full_load_rows") %in% names(memory_log)), "Memory log should record strategy and guardrail decisions.")
