root <- normalizePath(file.path(getwd()), winslash = "/", mustWork = FALSE)
Sys.setenv(DALYCARE_MIN_CELL_COUNT = "1")
source(file.path(root, "tests", "helper.R"))
source_test_runtime(root)

out_root <- tempfile("atlas_runs_")
result <- run_atlas(
  project_root = root,
  source_map_path = file.path(root, "config", "source-map.example.tsv"),
  output_root = out_root,
  mode = "report"
)

expect_file(file.path(result$run_dir, "outputs", "atlas_resource_catalog.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_sources.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_columns.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_checks.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_value_frequencies.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_run_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "lab_npu_code_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "diagnosis_icd_groups.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "damyda_feature_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "registry_clinical_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "damyda_clinical_profile.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "damyda_numeric_fields.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "lyfo_clinical_profile.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "cll_clinical_profile.csv"))
expect_file(file.path(result$run_dir, "outputs", "output_manifest.csv"))
expect_file(file.path(result$run_dir, "logs", "atlas_execution_log.tsv"))
expect_file(result$html)
expect_file(result$payload)

html <- paste(readLines(result$html, warn = FALSE), collapse = "\n")
expect_true(grepl("DALYCARE_atlas_payload.js", html, fixed = TRUE), "HTML should reference external payload JS.")
expect_false(grepl("window.DALYCARE_ATLAS_PAYLOAD =", html, fixed = TRUE), "HTML should not embed the full payload.")
expect_true(grepl("tab-overview", html, fixed = TRUE), "HTML should include the Overview tab.")
expect_true(grepl("tab-catalog", html, fixed = TRUE), "HTML should include the Source Catalog tab.")
expect_true(grepl("tab-registries", html, fixed = TRUE), "HTML should include the Registries tab.")
expect_true(grepl("tab-qa", html, fixed = TRUE), "HTML should include the Run QA tab.")
expect_true(grepl("tab-panels", html, fixed = TRUE), "HTML should include the Panels tab.")
expect_true(grepl("tab-quickstart", html, fixed = TRUE), "HTML should include the Quick Start tab.")
expect_true(grepl("catalog-search", html, fixed = TRUE), "HTML should include source catalog search.")
expect_true(grepl("catalog-domain-filter", html, fixed = TRUE), "HTML should include domain filtering controls.")
expect_true(grepl("catalog-status-filter", html, fixed = TRUE), "HTML should include status filtering controls.")
expect_true(grepl("catalog-role-filter", html, fixed = TRUE), "HTML should include role filtering controls.")
expect_true(grepl("qa-severity-filter", html, fixed = TRUE), "HTML should include QA filtering controls.")
expect_true(grepl("panel-nav", html, fixed = TRUE), "HTML should include panel navigation.")
payload <- paste(readLines(result$payload, warn = FALSE), collapse = "\n")
expect_true(grepl("damyda_clinical_profile", payload, fixed = TRUE), "Payload should include the DaMyDa clinical profile panel.")
expect_true(grepl("lyfo_clinical_profile", payload, fixed = TRUE), "Payload should include the LYFO clinical profile panel.")
expect_true(grepl("cll_clinical_profile", payload, fixed = TRUE), "Payload should include the CLL clinical profile panel.")
expect_true(grepl("run_summary", payload, fixed = TRUE), "Payload should include run summary rows.")
expect_true(grepl("source_domains", payload, fixed = TRUE), "Payload should include source-domain summaries.")
expect_true(grepl("hero_metrics", payload, fixed = TRUE), "Payload should include hero metrics.")
expect_true(grepl("domain_cards", payload, fixed = TRUE), "Payload should include domain cards.")
expect_true(grepl("catalog_rows", payload, fixed = TRUE), "Payload should include catalog rows.")
expect_true(grepl("qa_items", payload, fixed = TRUE), "Payload should include QA items.")
expect_true(grepl("registry_cards", payload, fixed = TRUE), "Payload should include registry cards.")
expect_true(grepl("panel_groups", payload, fixed = TRUE), "Payload should include panel groups.")
expect_false(grepl("patientid", payload, ignore.case = TRUE), "HTML payload should not expose id-like field names.")

freq <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_value_frequencies.csv"), stringsAsFactors = FALSE)
expect_false(any(freq$column_name == "patientid"), "Public value frequencies must not expose patient IDs.")

manifest <- utils::read.csv(file.path(result$run_dir, "outputs", "output_manifest.csv"), stringsAsFactors = FALSE)
expect_true(all(c("resource_catalog", "sources", "columns", "checks", "value_frequencies", "run_summary", "html", "payload") %in% manifest$artifact_id), "Manifest should list expected artifacts.")
expect_true(all(c("registry_clinical_summary", "damyda_clinical_profile", "damyda_numeric_fields", "lyfo_clinical_profile", "cll_clinical_profile") %in% manifest$artifact_id), "Manifest should list registry panel artifacts.")
expect_true(all(manifest$status == "ok"), "Manifest artifacts should exist.")

sources <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_sources.csv"), stringsAsFactors = FALSE)
expect_true(all(c("domain", "subdomain", "atlas_role") %in% names(sources)), "Source metadata should be preserved in atlas_sources.csv.")
expect_true(!any(sources$date_column_guess == "patientid"), "Patient identifiers should not be guessed as date columns.")
expect_true("2021-01-01" %in% sources$min_date, "Date ranges should be emitted as ISO dates.")

catalog <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_resource_catalog.csv"), stringsAsFactors = FALSE)
expect_true(all(c("domain", "subdomain", "atlas_role") %in% names(catalog)), "Source metadata should be preserved in the resource catalog.")

damyda_clinical <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "damyda_clinical_profile.csv"), stringsAsFactors = FALSE)
expect_true(any(damyda_clinical$facet == "stage"), "Run output should include DaMyDa stage summary.")
expect_false(any(damyda_clinical$source_column == "patientid"), "Run output registry panels must not expose patient identifier columns.")

damyda_numeric <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "damyda_numeric_fields.csv"), stringsAsFactors = FALSE)
expect_true(any(damyda_numeric$field == "albumin"), "Run output should include DaMyDa albumin aggregate summary.")
expect_false(any(c("value", "examples", "distinct_sample") %in% names(damyda_numeric)), "Run output numeric registry panel should be aggregate-only.")

run_summary <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_run_summary.csv"), stringsAsFactors = FALSE)
expect_true(all(c("mapped_sources", "loaded_sources", "panel_rows", "min_cell_count") %in% run_summary$metric), "Run summary should include compact run metrics.")
expect_true("1" %in% run_summary$value[run_summary$metric == "min_cell_count"], "Run summary should record the active minimum cell count.")

log_text <- paste(readLines(file.path(result$run_dir, "logs", "atlas_execution_log.tsv"), warn = FALSE), collapse = "\n")
expect_true(grepl("Run summary:", log_text, fixed = TRUE), "Execution log should include a run summary line.")
