root <- normalizePath(file.path(getwd()), winslash = "/", mustWork = FALSE)
Sys.setenv(DALYCARE_MIN_CELL_COUNT = "1")
source(file.path(root, "tests", "helper.R"))
source_test_runtime(root)

out_root <- tempfile("atlas_runs_")
result <- run_atlas(
  project_root = root,
  source_map_path = file.path(root, "config", "source-map.example.tsv"),
  output_root = out_root,
  mode = "report"
)

expect_file(file.path(result$run_dir, "outputs", "atlas_resource_catalog.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_source_resolution.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_dalycare_access.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_memory_plan.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_db_query_log.tsv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_db_budget_actions.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_sources.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_columns.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_column_profiles.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_column_top_values.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_checks.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_value_frequencies.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_run_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "atlas_run_action_items.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "lab_npu_code_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_dictionary_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_dictionary_vectors.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_lab_usage_by_vector.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_lab_unmatched_codes.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_detective_code_inventory.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_detective_candidates.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "npu_detective_source_year.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "isotype_code_usage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "isotype_bucket_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "mm_treatment_code_counts.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "mm_treatment_source_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "diagnosis_icd_groups.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "damyda_feature_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "registry_clinical_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "damyda_clinical_profile.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "damyda_numeric_fields.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "lyfo_clinical_profile.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "cll_clinical_profile.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_coverage_years.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_spatial_region_counts.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_spatial_region_coverage.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "atlas_dk_choropleth_regions.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "situation_report_summary.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "situation_report_breakdowns.csv"))
expect_file(file.path(result$run_dir, "outputs", "panels", "situation_report_freshness.csv"))
expect_file(file.path(result$run_dir, "outputs", "output_manifest.csv"))
expect_file(file.path(result$run_dir, "logs", "atlas_execution_log.tsv"))
expect_file(file.path(result$run_dir, "logs", "atlas_memory_log.tsv"))
expect_file(result$html)
expect_file(result$payload)

html <- paste(readLines(result$html, warn = FALSE), collapse = "\n")
expect_true(grepl("DALYCARE_atlas_payload.js", html, fixed = TRUE), "HTML should reference external payload JS.")
expect_false(grepl("window.DALYCARE_ATLAS_PAYLOAD =", html, fixed = TRUE), "HTML should not embed the full payload.")
expect_true(grepl("tab-overview", html, fixed = TRUE), "HTML should include the Overview tab.")
expect_true(grepl("tab-situation", html, fixed = TRUE), "HTML should include the Situation Report tab.")
expect_true(grepl("tab-quickstart", html, fixed = TRUE), "HTML should include the Quick Start tab.")
expect_true(grepl("tab-registries", html, fixed = TRUE), "HTML should include the Disease Registries tab.")
expect_true(grepl("tab-clinical", html, fixed = TRUE), "HTML should include the Clinical Data tab.")
expect_true(grepl("tab-treatment", html, fixed = TRUE), "HTML should include the Treatment tab.")
expect_true(grepl("tab-laboratory", html, fixed = TRUE), "HTML should include the Laboratory tab.")
expect_true(grepl("tab-ehr", html, fixed = TRUE), "HTML should include the EHR Modules tab.")
expect_true(grepl("tab-infrastructure", html, fixed = TRUE), "HTML should include the Infrastructure tab.")
expect_true(grepl("data-sub=\"overview-temporal\"", html, fixed = TRUE), "HTML should include temporal coverage sub-tabs.")
expect_true(grepl("data-sub=\"overview-spatial\"", html, fixed = TRUE), "HTML should include regional coverage sub-tabs.")
expect_true(grepl("data-sub=\"situation-headlines\"", html, fixed = TRUE), "HTML should include Situation Report sub-tabs.")
expect_true(grepl("data-sub=\"reg-damyda\"", html, fixed = TRUE), "HTML should include DaMyDa registry sub-tabs.")
expect_true(grepl("data-sub=\"clinical-diagnoses\"", html, fixed = TRUE), "HTML should include clinical module sub-tabs.")
expect_true(grepl("data-sub=\"tx-codes\"", html, fixed = TRUE), "HTML should include treatment-code sub-tabs.")
expect_true(grepl("data-sub=\"lab-npu\"", html, fixed = TRUE), "HTML should include laboratory/NPU sub-tabs.")
expect_true(grepl("data-sub=\"ehr-sp\"", html, fixed = TRUE), "HTML should include EHR module sub-tabs.")
expect_true(grepl("data-sub=\"infra-actions\"", html, fixed = TRUE), "HTML should include run action item sub-tabs.")
expect_true(grepl("data-sub=\"infra-catalog\"", html, fixed = TRUE), "HTML should include infrastructure sub-tabs.")
expect_true(grepl("catalog-search", html, fixed = TRUE), "HTML should include source catalog search.")
expect_true(grepl("catalog-domain-filter", html, fixed = TRUE), "HTML should include domain filtering controls.")
expect_true(grepl("catalog-status-filter", html, fixed = TRUE), "HTML should include status filtering controls.")
expect_true(grepl("catalog-role-filter", html, fixed = TRUE), "HTML should include role filtering controls.")
expect_true(grepl("column-search", html, fixed = TRUE), "HTML should include column search.")
expect_true(grepl("column-dataset-filter", html, fixed = TRUE), "HTML should include column dataset filtering.")
expect_true(grepl("column-domain-filter", html, fixed = TRUE), "HTML should include column domain filtering.")
expect_true(grepl("column-kind-filter", html, fixed = TRUE), "HTML should include column profile-kind filtering.")
expect_true(grepl("qa-severity-filter", html, fixed = TRUE), "HTML should include QA filtering controls.")
expect_true(grepl("run-action-items", html, fixed = TRUE), "HTML should include action item containers.")
expect_true(grepl("action-summary-cards", html, fixed = TRUE), "HTML should include action item summary cards.")
expect_true(grepl("panel-nav", html, fixed = TRUE), "HTML should include panel navigation.")
expect_true(grepl("temporal-heatmap", html, fixed = TRUE), "HTML should include a temporal coverage heatmap container.")
expect_true(grepl("dkMap", html, fixed = TRUE), "HTML should include a Denmark choropleth container.")
expect_true(grepl("regionMatrix", html, fixed = TRUE), "HTML should include a region coverage matrix container.")
expect_true(grepl("dk-region", html, fixed = TRUE), "HTML should include clickable Denmark region handlers.")
expect_true(grepl("situation-cards", html, fixed = TRUE), "HTML should include Situation Report card containers.")
expect_true(grepl("of cohort", html, fixed = TRUE), "Situation Report cards should show patient counts as a share of the cohort.")
expect_true(grepl("data as of", html, fixed = TRUE), "Situation Report cards should label source dates as data-as-of anchors.")
payload <- paste(readLines(result$payload, warn = FALSE), collapse = "\n")
expect_true(grepl("damyda_clinical_profile", payload, fixed = TRUE), "Payload should include the DaMyDa clinical profile panel.")
expect_true(grepl("lyfo_clinical_profile", payload, fixed = TRUE), "Payload should include the LYFO clinical profile panel.")
expect_true(grepl("cll_clinical_profile", payload, fixed = TRUE), "Payload should include the CLL clinical profile panel.")
expect_true(grepl("run_summary", payload, fixed = TRUE), "Payload should include run summary rows.")
expect_true(grepl("action_items", payload, fixed = TRUE), "Payload should include run action items.")
expect_true(grepl("action_summary", payload, fixed = TRUE), "Payload should include action item summaries.")
expect_true(grepl("db_query_log", payload, fixed = TRUE), "Payload should include DB query log diagnostics.")
expect_true(grepl("db_budget_actions", payload, fixed = TRUE), "Payload should include DB budget action diagnostics.")
expect_true(grepl("source_domains", payload, fixed = TRUE), "Payload should include source-domain summaries.")
expect_true(grepl("hero_metrics", payload, fixed = TRUE), "Payload should include hero metrics.")
expect_true(grepl("domain_cards", payload, fixed = TRUE), "Payload should include domain cards.")
expect_true(grepl("catalog_rows", payload, fixed = TRUE), "Payload should include catalog rows.")
expect_true(grepl("qa_items", payload, fixed = TRUE), "Payload should include QA items.")
expect_true(grepl("npu_cards", payload, fixed = TRUE), "Payload should include NPU dictionary cards.")
expect_true(grepl("detective_cards", payload, fixed = TRUE), "Payload should include NPU detective cards.")
expect_true(grepl("isotype_cards", payload, fixed = TRUE), "Payload should include isotype cards.")
expect_true(grepl("treatment_cards", payload, fixed = TRUE), "Payload should include treatment-code cards.")
expect_true(grepl("situation_report_cards", payload, fixed = TRUE), "Payload should include Situation Report cards.")
expect_true(grepl("registry_cards", payload, fixed = TRUE), "Payload should include registry cards.")
expect_true(grepl("panel_groups", payload, fixed = TRUE), "Payload should include panel groups.")
expect_true(grepl("column_profile_rows", payload, fixed = TRUE), "Payload should include column profile rows.")
expect_true(grepl("column_top_value_rows", payload, fixed = TRUE), "Payload should include column top value rows.")
expect_true(grepl("column_profile_summary", payload, fixed = TRUE), "Payload should include column profile summary.")
expect_true(grepl("aot_nav", payload, fixed = TRUE), "Payload should include V33-style navigation.")
expect_true(grepl("aot_overview", payload, fixed = TRUE), "Payload should include V33-style overview sections.")
expect_true(grepl("aot_registry_sections", payload, fixed = TRUE), "Payload should include V33-style registry sections.")
expect_true(grepl("aot_clinical_sections", payload, fixed = TRUE), "Payload should include V33-style clinical sections.")
expect_true(grepl("aot_treatment_sections", payload, fixed = TRUE), "Payload should include V33-style treatment sections.")
expect_true(grepl("aot_laboratory_sections", payload, fixed = TRUE), "Payload should include V33-style laboratory sections.")
expect_true(grepl("aot_situation_sections", payload, fixed = TRUE), "Payload should include V33-style Situation Report sections.")
expect_true(grepl("aot_ehr_sections", payload, fixed = TRUE), "Payload should include V33-style EHR sections.")
expect_true(grepl("aot_infrastructure_sections", payload, fixed = TRUE), "Payload should include V33-style infrastructure sections.")
expect_true(grepl("aot_temporal_coverage", payload, fixed = TRUE), "Payload should include V33-style temporal coverage sections.")
expect_true(grepl("aot_spatial_coverage", payload, fixed = TRUE), "Payload should include V33-style spatial coverage sections.")
expect_true(grepl("aot_dk_choropleth", payload, fixed = TRUE), "Payload should include V33-style Denmark choropleth sections.")
expect_false(grepl("patientid", payload, ignore.case = TRUE), "HTML payload should not expose id-like field names.")

freq <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_value_frequencies.csv"), stringsAsFactors = FALSE)
expect_false(any(freq$column_name == "patientid"), "Public value frequencies must not expose patient IDs.")

manifest <- utils::read.csv(file.path(result$run_dir, "outputs", "output_manifest.csv"), stringsAsFactors = FALSE)
expect_true(all(c("resource_catalog", "source_resolution", "dalycare_access", "memory_plan", "db_query_log", "db_budget_actions", "action_items", "sources", "columns", "column_profiles", "column_top_values", "checks", "value_frequencies", "run_summary", "html", "payload", "memory_log") %in% manifest$artifact_id), "Manifest should list expected artifacts.")
expect_true(all(c("npu_dictionary_summary", "npu_dictionary_vectors", "npu_lab_usage_by_vector", "npu_lab_unmatched_codes", "npu_detective_code_inventory", "npu_detective_candidates", "npu_detective_source_year", "isotype_code_usage", "isotype_bucket_summary", "mm_treatment_code_counts", "mm_treatment_source_summary", "registry_clinical_summary", "damyda_clinical_profile", "damyda_numeric_fields", "lyfo_clinical_profile", "cll_clinical_profile") %in% manifest$artifact_id), "Manifest should list NPU, isotype, treatment, and registry panel artifacts.")
expect_true(all(c("atlas_temporal_coverage", "atlas_temporal_coverage_years", "atlas_spatial_region_counts", "atlas_spatial_region_coverage", "atlas_dk_choropleth_regions") %in% manifest$artifact_id), "Manifest should list V33 coverage panel artifacts.")
expect_true(all(c("situation_report_summary", "situation_report_breakdowns", "situation_report_freshness") %in% manifest$artifact_id), "Manifest should list Situation Report panel artifacts.")
expect_true(all(manifest$status == "ok"), "Manifest artifacts should exist.")

sources <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_sources.csv"), stringsAsFactors = FALSE)
expect_true(all(c("domain", "subdomain", "atlas_role") %in% names(sources)), "Source metadata should be preserved in atlas_sources.csv.")
expect_true(all(c("chosen_strategy", "memory_status", "resolution_status") %in% names(sources)), "Source rows should record memory-safe profiling decisions.")
expect_true(!any(sources$date_column_guess == "patientid"), "Patient identifiers should not be guessed as date columns.")
expect_true("2021-01-01" %in% sources$min_date, "Date ranges should be emitted as ISO dates.")

columns <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_columns.csv"), stringsAsFactors = FALSE)
column_profiles <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_column_profiles.csv"), stringsAsFactors = FALSE)
column_top_values <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_column_top_values.csv"), stringsAsFactors = FALSE)
expect_equal(nrow(column_profiles), nrow(columns), "Run output should include one column profile per profiled column.")
expect_true(any(column_profiles$profile_kind == "numeric"), "Column profile output should include numeric summaries when numeric columns exist.")
expect_true(any(column_profiles$profile_kind == "date"), "Column profile output should include date summaries when date columns exist.")
expect_false(any(column_top_values$column_name == "patientid"), "Column top values must not expose patient identifier columns.")
expect_true(all(c("domain", "subdomain", "atlas_role") %in% names(column_profiles)), "Column profiles should retain source metadata.")

catalog <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_resource_catalog.csv"), stringsAsFactors = FALSE)
expect_true(all(c("domain", "subdomain", "atlas_role") %in% names(catalog)), "Source metadata should be preserved in the resource catalog.")

damyda_clinical <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "damyda_clinical_profile.csv"), stringsAsFactors = FALSE)
expect_true(any(damyda_clinical$facet == "stage"), "Run output should include DaMyDa stage summary.")
expect_false(any(damyda_clinical$source_column == "patientid"), "Run output registry panels must not expose patient identifier columns.")

damyda_numeric <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "damyda_numeric_fields.csv"), stringsAsFactors = FALSE)
expect_true(any(damyda_numeric$field == "albumin"), "Run output should include DaMyDa albumin aggregate summary.")
expect_false(any(c("value", "examples", "distinct_sample") %in% names(damyda_numeric)), "Run output numeric registry panel should be aggregate-only.")

npu_summary <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_dictionary_summary.csv"), stringsAsFactors = FALSE)
npu_vectors <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_dictionary_vectors.csv"), stringsAsFactors = FALSE)
npu_usage <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_lab_usage_by_vector.csv"), stringsAsFactors = FALSE)
npu_unmatched <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_lab_unmatched_codes.csv"), stringsAsFactors = FALSE)
npu_inventory <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_detective_code_inventory.csv"), stringsAsFactors = FALSE)
npu_candidates <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "npu_detective_candidates.csv"), stringsAsFactors = FALSE)
isotype_usage <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "isotype_code_usage.csv"), stringsAsFactors = FALSE)
isotype_buckets <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "isotype_bucket_summary.csv"), stringsAsFactors = FALSE)
mm_counts <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "mm_treatment_code_counts.csv"), stringsAsFactors = FALSE)
mm_sources <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "mm_treatment_source_summary.csv"), stringsAsFactors = FALSE)
temporal_coverage <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_coverage.csv"), stringsAsFactors = FALSE)
temporal_years <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_temporal_coverage_years.csv"), stringsAsFactors = FALSE)
spatial_counts <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_spatial_region_counts.csv"), stringsAsFactors = FALSE)
spatial_coverage <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_spatial_region_coverage.csv"), stringsAsFactors = FALSE)
dk_regions <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "atlas_dk_choropleth_regions.csv"), stringsAsFactors = FALSE)
expect_true("dictionary_codes" %in% npu_summary$metric, "Run output should include NPU dictionary summary.")
expect_true(any(npu_vectors$consensus_vector == "CREATININE_CODES"), "Run output should include NPU dictionary vector summaries.")
expect_true(any(npu_usage$consensus_vector == "CREATININE_CODES"), "Run output should include observed NPU usage by consensus vector.")
expect_true(any(npu_unmatched$npu_code == "NPU99999"), "Run output should include suppressed-safe unmatched NPU code summaries.")
expect_true(any(npu_inventory$surface == "renal_creatinine"), "Run output should include NPU detective surface classifications.")
expect_true(any(npu_candidates$npu_code == "NPU99999"), "Run output should include NPU detective candidates.")
expect_true(any(isotype_usage$isotype_family == "IgG"), "Run output should include isotype finder usage.")
expect_true(any(isotype_buckets$bucket == "heavy_chain"), "Run output should include isotype bucket summaries.")
expect_true(any(mm_counts$code == "BWHA154"), "Run output should count exact MM treatment codes.")
expect_true(any(mm_counts$code == "BWG"), "Run output should count MM treatment prefix codes.")
expect_true(nrow(mm_sources) > 0, "Run output should summarize treatment evidence sources.")
expect_true(any(temporal_coverage$table_name == "example_labs" & temporal_coverage$display_min_year == 2021), "Run output should include clamped temporal coverage by source.")
expect_true(any(temporal_years$table_name == "example_labs" & temporal_years$year == 2021), "Run output should include temporal coverage year counts.")
expect_true(any(spatial_counts$table_name == "example_damyda" & spatial_counts$region_code == "1084"), "Run output should include aggregate DaMyDa region counts.")
expect_true(any(spatial_coverage$region_code == "1084"), "Run output should include region coverage matrix rows.")
expect_equal(sum(as.logical(dk_regions$map_include)), 5L, "Denmark choropleth should include the five Danish regions.")
expect_false(any(dk_regions$region_code == "1099" & as.logical(dk_regions$map_include)), "Other/unknown region should not be shaded on the map.")

run_summary <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_run_summary.csv"), stringsAsFactors = FALSE)
expect_true(all(c("mapped_sources", "loaded_sources", "skipped_sources", "panel_rows", "min_cell_count", "db_aggregate_sources", "dataset_full_load_fallback_sources") %in% run_summary$metric), "Run summary should include compact run and memory metrics.")
expect_true("1" %in% run_summary$value[run_summary$metric == "min_cell_count"], "Run summary should record the active minimum cell count.")

action_items <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_run_action_items.csv"), stringsAsFactors = FALSE)
expect_true(all(c("severity", "action_id", "recommended_action") %in% names(action_items)), "Run action items should include severity, action id, and operator action columns.")

situation_summary <- utils::read.csv(file.path(result$run_dir, "outputs", "panels", "situation_report_summary.csv"), stringsAsFactors = FALSE)
expect_true(all(c("definition_basis", "n_cohort", "pct_cohort") %in% names(situation_summary)), "Situation Report summary should include definition and cohort-audit columns.")

log_text <- paste(readLines(file.path(result$run_dir, "logs", "atlas_execution_log.tsv"), warn = FALSE), collapse = "\n")
expect_true(grepl("Run summary:", log_text, fixed = TRUE), "Execution log should include a run summary line.")

memory_plan <- utils::read.csv(file.path(result$run_dir, "outputs", "atlas_memory_plan.csv"), stringsAsFactors = FALSE)
expect_true(all(memory_plan$chosen_strategy == "file_full_load"), "Fixture file sources should use the file full-load strategy.")
memory_log <- utils::read.delim(file.path(result$run_dir, "logs", "atlas_memory_log.tsv"), stringsAsFactors = FALSE)
expect_true(all(c("chosen_strategy", "memory_status", "max_full_load_rows") %in% names(memory_log)), "Memory log should record strategy and guardrail decisions.")
